services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
      - adminer_data:/var/www/adminer
    depends_on:
      - wordpress
    networks:
      - inception

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - redis
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_MAIL=${ADMIN_MAIL}
      - USER_MAIL=${USER_MAIL}
      - USER_USERNAME=${USER_USERNAME}
      - WEBSITE_NAME=${WEBSITE_NAME}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - ADMIN_PASS=${ADMIN_PASS}
      - USER_PASS=${USER_PASS}
    networks:
      - inception

  adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    volumes:
      - adminer_data:/var/www/adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    networks:
      - inception

  redis:
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    networks:
      - inception

  ftp:
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
      args:
        FTP_USER: ${FTP_USER}
        FTP_PASS: ${FTP_PASS}
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
    volumes:
      - wordpress_data:/home/${FTP_USER}
    networks:
      - inception

  cadvisor:
    build:
      context: ./requirements/bonus/cadvisor
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - inception
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker:/var/lib/docker:ro"

  myweb:
    build:
      context: ./requirements/bonus/myweb
      dockerfile: Dockerfile
    networks:
      - inception

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/mboukour/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/mboukour/data/mariadb
      o: bind
  adminer_data:
    driver: local
    driver_opts:
      type: none
      device: /home/mboukour/data/adminer
      o: bind

networks:
  inception:
    driver: bridge
    name: inception
