version: '3.8'

services:
  nginx:
    build:
      context: ./srcs/requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
      - adminer_data:/var/www/adminer
    depends_on:
      - wordpress

  mariadb:
    build:
      context: ./srcs/requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build:
      context: ./srcs/requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_MAIL=${ADMIN_MAIL}
      - USER_MAIL=${USER_MAIL}
      - USER_USERNAME=${USER_USERNAME}
      - WEBSITE_NAME=${WEBSITE_NAME}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}

  adminer:
    build:
      context: ./srcs/bonus/adminer
      dockerfile: Dockerfile
    ports:
      - "900:900"
    depends_on:
      - mariadb
    volumes:
      - adminer_data:/var/www/adminer
    

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ruined/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ruined/data/mariadb
      o: bind
  adminer_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ruined/data/adminer
      o: bind